<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" @class(['dark' => ($appearance ?? 'system') == 'dark'])>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">

    {{-- Favicon Links generated by RealFaviconGenerator.net (example) --}}
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">
<link rel="manifest" href="{{ asset('site.webmanifest') }}">
<link rel="mask-icon" href="{{ asset('safari-pinned-tab.svg') }}" color="#5bbad5"> {{-- If you have this file --}}
<meta name="msapplication-TileColor" content="#da532c"> {{-- If applicable --}}
<meta name="theme-color" content="#ffffff"> {{-- If applicable --}}
<link rel="icon" href="{{ asset('favicon.ico') }}" type="image/x-icon">
{{-- End Favicon Links --}}

        {{--
            Removed global <link rel="preload"> for loading-bg.png and sign-in-bg.jpg.
            Those are large backgrounds used by only one page each (dashboard / sign-in).
            Preloading them on every page blocks the single-threaded `php artisan serve`
            queue, which is why dashboard elements appeared to load slowly / partially.
            Each page's CSS `background-image: url(...)` fetches them when actually needed.
        --}}

        <style>
            html {
                background-color: #06212e;
            }

            html.dark {
                background-color: #06212e;
            }
        </style>

        <title>Radar LEB</title>

        @routes
        @vite(['resources/js/app.ts'])
        @inertiaHead
    </head>
    <body class="font-sans antialiased">
        @inertia
    </body>
</html>