<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" @class(['dark' => ($appearance ?? 'system') == 'dark'])>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
        <meta name="csrf-token" content="{{ csrf_token() }}">

    {{-- Favicon Links generated by RealFaviconGenerator.net (example) --}}
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-16x16.png') }}">
<link rel="manifest" href="{{ asset('site.webmanifest') }}">
<link rel="mask-icon" href="{{ asset('safari-pinned-tab.svg') }}" color="#5bbad5"> {{-- If you have this file --}}
<meta name="msapplication-TileColor" content="#06212e">
<meta name="theme-color" content="#06212e">

{{--
    Add-to-Home-Screen / PWA install hints. iOS Safari does not implement
    the `beforeinstallprompt` event, so we rely on these meta tags + the
    in-app `<AddToHomeScreenPrompt />` instructions banner. Without
    `apple-mobile-web-app-capable` the home-screen launch opens in regular
    Safari instead of the standalone PWA shell.
--}}
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="RadarLeb">
<link rel="icon" href="{{ asset('favicon.ico') }}" type="image/x-icon">
{{-- End Favicon Links --}}

        {{--
            Google Fonts preconnect + Bungee stylesheet. Hoisted out of
            Dashboard.vue: the original spot inserted these <link> tags into
            the rendered template on every Inertia visit, which caused the
            browser to re-resolve preconnects per navigation and briefly
            re-apply font-face mid-render. The layout is the right place —
            it's parsed once per full document load.
        --}}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bungee&display=swap" rel="stylesheet">

        {{--
            Removed global <link rel="preload"> for loading-bg.png and sign-in-bg.jpg.
            Those are large backgrounds used by only one page each (dashboard / sign-in).
            Preloading them on every page blocks the single-threaded `php artisan serve`
            queue, which is why dashboard elements appeared to load slowly / partially.
            Each page's CSS `background-image: url(...)` fetches them when actually needed.
        --}}

        <style>
            html {
                background-color: #06212e;
            }

            html.dark {
                background-color: #06212e;
            }
        </style>

        <title>Radar LEB</title>

        @routes
        @vite(['resources/js/app.ts'])
        @inertiaHead
    </head>
    <body class="font-sans antialiased">
        @inertia
    </body>
</html>