#!/usr/bin/env bash
# RadarLeb — Cleanup phase 2: nuke root-level junk.
#
# Approach: whitelist the files/dirs that legitimately live at the project root,
# `git rm -f` everything else. The Laravel/Vue app does not autoload anything
# from the project root (PSR-4 -> app/, Vite -> resources/js/), so deleting the
# 125 stray .vue + 58 stray .php + 18 stray .js/.ts/.css + 22 .md files at root
# does NOT change runtime behavior. Git history preserves all of it if we ever
# need to recover something.
#
# Run from project root: bash scripts/cleanup-phase-2.sh

set -euo pipefail

GREEN="\033[0;32m"; RED="\033[0;31m"; YELLOW="\033[0;33m"; BLUE="\033[0;34m"; RESET="\033[0m"
say()  { printf "${BLUE}==>${RESET} %s\n" "$1"; }
ok()   { printf "${GREEN}✓${RESET}  %s\n" "$1"; }
warn() { printf "${YELLOW}!${RESET}  %s\n" "$1"; }
die()  { printf "${RED}✗${RESET}  %s\n" "$1"; exit 1; }

cd "$(dirname "$0")/.."
[ -d .git ] || die "must be run from the project root (no .git here)"

# Files that legitimately live at the repo root.
KEEP=(
  .env
  .env.example
  .env.local
  .gitignore
  .gitattributes
  .editorconfig
  .prettierrc
  .prettierignore
  .npmrc
  AGENTS.md
  CLAUDE.md
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE
  README.md
  artisan
  components.json
  composer.json
  composer.lock
  docker-compose.yml
  Dockerfile
  eslint.config.js
  package.json
  package-lock.json
  phpunit.xml
  tsconfig.json
  vite.config.ts
  .cursorrules
)

# Whitelist directories at root.
KEEP_DIRS=(
  .git .github .vscode .idea .cursor
  app bootstrap config database docs node_modules public resources routes
  scripts storage tests vendor
)

is_kept() {
  local f="$1"
  for k in "${KEEP[@]}"; do
    [ "$f" = "$k" ] && return 0
  done
  return 1
}

# -----------------------------------------------------------------------------
# 1. Collect everything at depth 1 that is NOT in the keep list
# -----------------------------------------------------------------------------
say "Scanning project root for cleanup targets"

# Files (depth 1). Use BSD-find friendly invocation (no -printf), strip leading
# ./ with sed. Read into an array via a portable `while read` loop because
# `mapfile` does not exist on bash 3.2 (the macOS default).
TARGETS=()
while IFS= read -r line; do
  TARGETS+=("$line")
done < <(
  find . -maxdepth 1 -type f -not -name '.DS_Store' \
    | sed 's|^\./||' \
    | grep -vE '^(\.|\.\.|\..*\.swp)$' \
    | sort
)

DELETE=()
SKIP=()
for f in "${TARGETS[@]}"; do
  if is_kept "$f"; then
    SKIP+=("$f")
  else
    DELETE+=("$f")
  fi
done

echo "  ${#SKIP[@]} root files kept (whitelist)"
echo "  ${#DELETE[@]} root files to delete"
echo ""

if [ "${#DELETE[@]}" -eq 0 ]; then
  ok "Nothing to clean at root"
else
  echo "First 30 to-delete:"
  printf '    %s\n' "${DELETE[@]:0:30}"
  if [ "${#DELETE[@]}" -gt 30 ]; then
    echo "    ...and $((${#DELETE[@]} - 30)) more"
  fi
fi

# -----------------------------------------------------------------------------
# 2. Delete via git rm so renames/deletes are tracked
# -----------------------------------------------------------------------------
say "Removing junk files (tracked + untracked)"
DELETED=0
for f in "${DELETE[@]}"; do
  if git ls-files --error-unmatch "$f" >/dev/null 2>&1; then
    git rm -f -- "$f" >/dev/null 2>&1 || warn "git rm failed for $f"
  else
    rm -f -- "$f"
  fi
  DELETED=$((DELETED+1))
done
ok "$DELETED root files removed"

# -----------------------------------------------------------------------------
# 3. Tighten .gitignore — Laravel/Vite-generated runtime stuff that should
#    never be tracked, plus IDE/OS noise.
# -----------------------------------------------------------------------------
say "Rewriting .gitignore"
cat > .gitignore <<'GITIGNORE'
# ---- Dependencies ----
/node_modules
/vendor
/public/build
/public/hot
/public/storage

# Filament publishes its compiled assets into public/{js,css}/filament — those
# are generated by `php artisan filament:upgrade`, never edited by hand.
/public/css/filament
/public/js/filament

# ---- Environment ----
.env
.env.backup
.env.production
.env.*
!.env.example

# ---- Secrets / credentials ----
auth.json
*.pem
*.p12
*.key
/storage/*.key

# ---- Laravel runtime caches ----
/bootstrap/cache/*
!/bootstrap/cache/.gitignore
/storage/app/*
!/storage/app/private/
!/storage/app/public/
/storage/app/private/*
/storage/app/public/*
!/storage/app/.gitignore
!/storage/app/private/.gitignore
!/storage/app/public/.gitignore
/storage/framework/cache/*
!/storage/framework/cache/.gitignore
/storage/framework/cache/data/*
!/storage/framework/cache/data/.gitignore
/storage/framework/sessions/*
!/storage/framework/sessions/.gitignore
/storage/framework/testing/*
!/storage/framework/testing/.gitignore
/storage/framework/views/*
!/storage/framework/views/.gitignore
/storage/logs/*
!/storage/logs/.gitignore
/storage/pail/*
!/storage/pail/.gitignore
/storage/debugbar/*
!/storage/debugbar/.gitignore

# ---- Local SQLite database ----
/database/database.sqlite
/database/database.sqlite-journal

# ---- Test caches ----
.phpunit.result.cache
.phpunit.cache/

# ---- IDE / OS ----
/.fleet
/.idea
/.vscode
/.zed
.DS_Store
Thumbs.db
*.swp
*.swo

# ---- Homestead/Sail leftovers ----
Homestead.json
Homestead.yaml
npm-debug.log
yarn-error.log

# ---- Editor backup files left at root ----
* 2.*
* copy.*
GITIGNORE
ok ".gitignore tightened"

# -----------------------------------------------------------------------------
# 4. Stop tracking files that should have been ignored all along.
# -----------------------------------------------------------------------------
say "Stop tracking files that newly match .gitignore"
git rm -r --cached --quiet \
  bootstrap/cache 2>/dev/null || true
git rm --cached --quiet \
  database/database.sqlite \
  storage/logs/laravel.log 2>/dev/null || true

# Re-add the .gitkeep / .gitignore stubs so the directories still exist.
mkdir -p bootstrap/cache storage/framework/{cache/data,sessions,testing,views} storage/logs storage/pail storage/app/{public,private}
for d in bootstrap/cache storage/framework/cache storage/framework/cache/data storage/framework/sessions storage/framework/testing storage/framework/views storage/logs storage/pail storage/app storage/app/public storage/app/private; do
  [ -f "$d/.gitignore" ] || cat > "$d/.gitignore" <<'STUB'
*
!.gitignore
STUB
  git add -f "$d/.gitignore" >/dev/null 2>&1 || true
done
ok "Runtime directories preserved with .gitignore stubs"

# -----------------------------------------------------------------------------
# 5. Stage the cleanup commit
# -----------------------------------------------------------------------------
say "Staging .gitignore + scripts"
git add .gitignore
git add scripts/cleanup-phase-2.sh

# -----------------------------------------------------------------------------
# 6. Summary
# -----------------------------------------------------------------------------
echo ""
say "Cleanup phase 2 staged. Inspect with:  git status  /  git diff --cached --stat"
echo ""
echo "When happy, commit with:"
echo "  git commit -m 'Clean up root: nuke 200+ stray files + tighten .gitignore'"
